# Generated by Django 5.1.2 on 2026-06-06 11:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Model",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "model_name",
                    models.CharField(db_index=True, max_length=64, unique=True),
                ),
                ("description", models.TextField(blank=True, default="")),
                (
                    "task_type",
                    models.CharField(
                        choices=[
                            ("binary_classification", "Binary classification"),
                            ("multiclass_classification", "Multiclass classification"),
                            ("regression", "Regression"),
                        ],
                        default="binary_classification",
                        max_length=32,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                "ordering": ["model_name"],
            },
        ),
        migrations.CreateModel(
            name="ModelVersion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("version", models.CharField(max_length=32)),
                ("artifact_path", models.CharField(max_length=255)),
                ("trained_at", models.DateTimeField(blank=True, null=True)),
                (
                    "training_dataset_ref",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                ("metrics_at_training", models.JSONField(blank=True, default=dict)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("CANDIDATE", "Candidate"),
                            ("STABLE", "Stable"),
                            ("ACTIVE", "Active"),
                            ("DEPRECATED", "Deprecated"),
                            ("ROLLED_BACK", "Rolled back"),
                        ],
                        db_index=True,
                        default="CANDIDATE",
                        max_length=16,
                    ),
                ),
                ("is_active", models.BooleanField(db_index=True, default=False)),
                (
                    "endpoint_url",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                ("port", models.PositiveIntegerField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "model",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="versions",
                        to="registry_app.model",
                    ),
                ),
            ],
            options={
                "ordering": ["model__model_name", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ActiveModelPointer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("switched_at", models.DateTimeField(auto_now=True)),
                ("switched_by", models.CharField(default="agent", max_length=64)),
                (
                    "model_version",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="active_pointer",
                        to="registry_app.modelversion",
                    ),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name="modelversion",
            constraint=models.UniqueConstraint(
                fields=("model", "version"), name="uq_modelversion_model_version"
            ),
        ),
        migrations.AddConstraint(
            model_name="modelversion",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_active", True)),
                fields=("model",),
                name="uq_one_active_version_per_model",
            ),
        ),
    ]
