# Generated by Django 5.1.2 on 2026-06-20 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("registry_app", "0001_initial"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="modelversion",
            name="uq_one_active_version_per_model",
        ),
        migrations.AddConstraint(
            model_name="modelversion",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_active", True)),
                fields=("is_active",),
                name="uq_one_global_active_version",
            ),
        ),
    ]
