# Generated by Django 5.1.2 on 2026-06-06 11:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("monitoring_app", "0001_initial"),
        ("registry_app", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Incident",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("opened_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("closed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("OPEN", "Open"),
                            ("RECOVERING", "Recovering"),
                            ("VERIFYING", "Verifying"),
                            ("RESOLVED", "Resolved"),
                            ("ESCALATED", "Escalated"),
                        ],
                        db_index=True,
                        default="OPEN",
                        max_length=16,
                    ),
                ),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("LOW", "Low"),
                            ("MEDIUM", "Medium"),
                            ("HIGH", "High"),
                            ("CRITICAL", "Critical"),
                        ],
                        db_index=True,
                        default="LOW",
                        max_length=8,
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("DATA_DRIFT", "Data drift"),
                            ("CONCEPT_DRIFT", "Concept drift"),
                            ("ANOMALY", "Anomaly"),
                            ("THRESHOLD", "Threshold breach"),
                            ("AVAILABILITY", "Availability / health"),
                            ("UNKNOWN", "Unknown"),
                        ],
                        default="UNKNOWN",
                        max_length=24,
                    ),
                ),
                ("root_cause", models.TextField(blank=True, default="")),
                (
                    "affected_version",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="incidents",
                        to="registry_app.modelversion",
                    ),
                ),
            ],
            options={
                "ordering": ["-opened_at"],
            },
        ),
        migrations.CreateModel(
            name="ActionLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("NO_OP", "No-op"),
                            ("ALERT", "Alert only"),
                            ("SWITCH", "Switch active model"),
                            ("ROLLBACK", "Rollback version"),
                            ("RETRAIN", "Retrain"),
                            ("DISABLE", "Disable predictions"),
                        ],
                        db_index=True,
                        max_length=16,
                    ),
                ),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("LOW", "Low"),
                            ("MEDIUM", "Medium"),
                            ("HIGH", "High"),
                            ("CRITICAL", "Critical"),
                        ],
                        max_length=8,
                    ),
                ),
                ("reason", models.TextField()),
                ("decided_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("executed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "outcome",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("SUCCESS", "Success"),
                            ("FAILED", "Failed"),
                            ("REVERTED", "Reverted"),
                        ],
                        db_index=True,
                        default="PENDING",
                        max_length=8,
                    ),
                ),
                (
                    "jenkins_build_id",
                    models.CharField(blank=True, default="", max_length=64),
                ),
                ("before_metrics", models.JSONField(blank=True, default=dict)),
                ("after_metrics", models.JSONField(blank=True, default=dict)),
                ("is_reversible", models.BooleanField(default=True)),
                (
                    "model_version",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="actions",
                        to="registry_app.modelversion",
                    ),
                ),
                (
                    "reverted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reverts",
                        to="actions_app.actionlog",
                    ),
                ),
                (
                    "incident",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="actions",
                        to="actions_app.incident",
                    ),
                ),
            ],
            options={
                "ordering": ["-decided_at"],
            },
        ),
        migrations.CreateModel(
            name="VerificationResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("verified_at", models.DateTimeField(auto_now_add=True)),
                ("post_metrics", models.JSONField(default=dict)),
                ("success", models.BooleanField()),
                (
                    "decision",
                    models.CharField(
                        choices=[
                            ("KEEP", "Keep"),
                            ("REVERT", "Revert"),
                            ("ESCALATE", "Escalate"),
                        ],
                        max_length=8,
                    ),
                ),
                (
                    "action",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="verification",
                        to="actions_app.actionlog",
                    ),
                ),
                (
                    "baseline_ref",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="verifications",
                        to="monitoring_app.baseline",
                    ),
                ),
            ],
            options={
                "ordering": ["-verified_at"],
            },
        ),
    ]
