# Generated by Django 5.1.2 on 2026-06-20 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("actions_app", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="actionlog",
            name="outcome",
            field=models.CharField(
                choices=[
                    ("PENDING", "Pending"),
                    ("SUCCESS", "Success"),
                    ("FAILED", "Failed"),
                    ("SKIPPED", "Skipped"),
                    ("REVERTED", "Reverted"),
                ],
                db_index=True,
                default="PENDING",
                max_length=8,
            ),
        ),
    ]
