# Generated by Django 5.1.2 on 2026-06-06 11:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("registry_app", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="MetricSnapshot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("timestamp", models.DateTimeField(db_index=True)),
                ("window_seconds", models.PositiveIntegerField(default=60)),
                ("request_count", models.PositiveIntegerField(default=0)),
                ("error_count", models.PositiveIntegerField(default=0)),
                ("error_rate", models.FloatField(default=0.0)),
                ("avg_latency_ms", models.FloatField(default=0.0)),
                ("p95_latency_ms", models.FloatField(default=0.0)),
                ("avg_confidence", models.FloatField(blank=True, null=True)),
                ("accuracy", models.FloatField(blank=True, null=True)),
                ("f1", models.FloatField(blank=True, null=True)),
                ("rmse", models.FloatField(blank=True, null=True)),
                ("missing_rate", models.FloatField(default=0.0)),
                ("out_of_range_rate", models.FloatField(default=0.0)),
                ("overall_drift_score", models.FloatField(default=0.0)),
                ("drifted_feature_count", models.PositiveIntegerField(default=0)),
                (
                    "health_status",
                    models.CharField(
                        choices=[
                            ("HEALTHY", "Healthy"),
                            ("DEGRADED", "Degraded"),
                            ("UNHEALTHY", "Unhealthy"),
                            ("UNKNOWN", "Unknown"),
                        ],
                        db_index=True,
                        default="HEALTHY",
                        max_length=16,
                    ),
                ),
                ("raw", models.JSONField(blank=True, default=dict)),
                (
                    "model_version",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="snapshots",
                        to="registry_app.modelversion",
                    ),
                ),
            ],
            options={
                "ordering": ["-timestamp"],
                "get_latest_by": "timestamp",
            },
        ),
        migrations.CreateModel(
            name="FeatureDriftScore",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("feature_name", models.CharField(max_length=128)),
                ("psi", models.FloatField(blank=True, null=True)),
                ("ks_stat", models.FloatField(blank=True, null=True)),
                ("ks_pvalue", models.FloatField(blank=True, null=True)),
                ("drifted", models.BooleanField(db_index=True, default=False)),
                (
                    "snapshot",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="feature_drift",
                        to="monitoring_app.metricsnapshot",
                    ),
                ),
            ],
            options={
                "ordering": ["snapshot", "feature_name"],
            },
        ),
        migrations.CreateModel(
            name="Baseline",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("captured_at", models.DateTimeField(auto_now_add=True)),
                ("is_current", models.BooleanField(db_index=True, default=True)),
                ("metrics", models.JSONField(default=dict)),
                ("ref_accuracy", models.FloatField(blank=True, null=True)),
                ("ref_error_rate", models.FloatField(blank=True, null=True)),
                ("ref_p95_latency_ms", models.FloatField(blank=True, null=True)),
                ("note", models.CharField(blank=True, default="", max_length=255)),
                (
                    "model_version",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="baselines",
                        to="registry_app.modelversion",
                    ),
                ),
            ],
            options={
                "ordering": ["-captured_at"],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("is_current", True)),
                        fields=("model_version",),
                        name="uq_one_current_baseline_per_version",
                    )
                ],
            },
        ),
        migrations.AddIndex(
            model_name="metricsnapshot",
            index=models.Index(
                fields=["model_version", "-timestamp"], name="idx_snap_version_ts"
            ),
        ),
        migrations.AddIndex(
            model_name="metricsnapshot",
            index=models.Index(fields=["health_status"], name="idx_snap_health"),
        ),
        migrations.AddConstraint(
            model_name="featuredriftscore",
            constraint=models.UniqueConstraint(
                fields=("snapshot", "feature_name"), name="uq_drift_snapshot_feature"
            ),
        ),
    ]
